---
title: "Physiospace Web Interface"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(PhysioSpaceMethods)
require(HumanPhysioSpace)
require(PlantPhysioSpace)
require(parallel)
# Allow upload of 1GB tables
options(shiny.maxRequestSize=1024^3) 
# Allow for maximum parallel computation - use all available cores
options(mc.cores=detectCores())
```

Please upload your table (max. 1GB). For details on how to prepare it, please consult the
Vignette of the R package `PhysioSpaceMethods`.

```{r, echo = FALSE}
fileInput("file1", "Choose CSV File",
          multiple = TRUE,
          accept = c("text/csv",
                     "text/comma-separated-values,text/plain",
                     ".csv")
)

sliderInput("absCutoff", "")

calc.physio.map <- reactive({
  if(! is.null(input$file1$datapath)) {
    # Create a Progress object
    progress <- shiny::Progress$new()
    # Make sure it closes when we exit this reactive, even if there's an error
    on.exit(progress$close())
    # Show progress message
    progress$set(message = "Analyzing data. This can take a while..", value = 0)
    # Read uploaded data as matrix
    counts.df <- as.matrix(
      read.table(
        input$file1$datapath, sep=",", quote='"', comment.char='', header = TRUE, 
        stringsAsFactors = FALSE)
    )
    # row-names must be gene names in the first column
    rownames(counts.df) <- counts.df[,1]
    # Normalize read counts as deviations from mean
    counts.relative <- counts.df - apply(counts.df, 1, mean)
    # Calculate the Physiospace Map
    calculatePhysioMap(
      InputData = counts.relative, 
      Space = HS_LUKK_Space, PARALLEL = T, 
      NumbrOfCores = getOption("mc.cores", 1)
    )
  }
})


renderPlot({
  # Plot the results
  # Choosing 5 random samples:
  set.seed(seed = 0) # So results would be reproducible 
  physio.map <- calc.physio.map()
  if (!is.null(physio.map)) {
    RESULTS5Random <- physio.map[,sample(x = 1:ncol(physio.map), size = 5)]
    #Plotting the results:
    PhysioHeatmap(PhysioResults = RESULTS5Random, main = "RNA-seq vs Microarray",
                  SymmetricColoring = T, SpaceClustering = T, Space = HS_LUKK_Space,
                  ReducedPlotting = 5
    )
  }
})
  
```